### ISSUE TITLE
Allow passing .hemrc via commandline-flag

### ISSUE THREAD

**Issue by mborejdo** [jahzielv/hemingway#10]
This feature would allow fine-grained feed config, running multiple hem-instances with different feed-configs.

**Comment by jahzielv** [comment]
I dig this! I was just thinking of a way to have a little bit more control over the feeds you're saving. 
What do you think about having categories within the feeds so that you could still store everything in one single file, but could run something like 
```bash
$ hem -c software
```
and it would print all your feed updates for that "software" category?

**Comment by mborejdo** [comment]
yea! that is ultimately what i want to achieve. I have news-feeds, github releases, etc, which i want to separate and have different hemingway instances rendering the data.
Categories might make the add subcommand more complicated? Which category should the feed be added to? How do we add categories? Maybe have some kind of generic tagging per feed one can filter? I thought separate configs might be the easiest way to achieve the separation

**Comment by jahzielv** [comment]
> different hemingway instances rendering the data

By this, do you mean different binaries installed on your computer?

**Comment by mborejdo** [comment]
> > different hemingway instances rendering the data
> 
> By this, do you mean different binaries installed on your computer?

No. Thats not my usecase. Bad wording :-)
I wanted to do something like:

```
hem --config ~/.config/hemingway/releases.json
hem --config ~/.config/hemingway/news.json
hem --config ~/.config/hemingway/jenkins.json
```

Running in different terminalemulators

**Comment by jahzielv** [comment]
Ahh ok gotcha! Thanks for clarifying!

I'm personally more up for having categories than separate files, if for nothing else than neatness :)

I'm thinking that having categories would expand the API about the same as having separate files, since you'd still have to have a way to indicate which file or category you want to add a feed. I'm picturing something like this:
```bash
$ hem add -c software https://example.com/softwarefeed
```
This would add the feed to a subarray within the `feeds` array in `.hemrc` called `software`. If the array doesn't exist yet, Hemingway will create it. To check for updates for a category, 
```bash
$ hem -c software
```
Running `hem` with no flags would have the same behavior as now. What do you think?

**Comment by mborejdo** [comment]
I personally don't like too complex configs. Adding these things via config, makes it error prone, hard to edit manually, etc. Otoh the timestamp needs to be tracked somehow, so I guess there is no better way to keep track of the data (without using some cache/db or something) than the config. So I'm super happy with added categories to the config to have more control over the rendered data. Also thanks for the speed improvements :-)

**Comment by jahzielv** [comment]
Thanks for your thoughts!! I agree there is a tradeoff no matter what; I may spend some time looking into alternative data storage methods.

> Also thanks for the speed improvements :-)

My pleasure! I'm glad it wasn't just me that got some benefit from that code tweaking :)
